import {
  DEFAULT_PYRAMID_COLOR,
  DEFAULT_BRIGHTNESS,
  DEFAULT_SLICE_GRADIENTS,
  DEFAULT_SLICE_OPACITY,
  DEFAULT_AXIS_SETTINGS,
  DEFAULT_EDGE_FLOW_SETTINGS,
  PYRAMID_EFFECT_MODES
} from '../config/constants.js';

export const state = {
  pyramidColorHex: DEFAULT_PYRAMID_COLOR,
  pyramidBrightness: DEFAULT_BRIGHTNESS,
  sliceGradients: DEFAULT_SLICE_GRADIENTS.map((g) => ({ ...g })),
  sliceOpacity: { ...DEFAULT_SLICE_OPACITY },
  axisSettings: { ...DEFAULT_AXIS_SETTINGS },
  edgeFlowSettings: { ...DEFAULT_EDGE_FLOW_SETTINGS },
  pyramidEffectMode: PYRAMID_EFFECT_MODES.GLOW,
  pyramidGroups: { glow: null, wireframe: null, particles: null },
  glowObjects: null,
  pyramidMats: {},
  pyramidLights: {},
  bloomPass: null,
  fxaaPass: null,
  labelElements: [],
  clock: null,
  pyramidApex: null,
  pyramidBaseVerts: null,
  internalParticleGeo: null,
  internalParticleStreams: [],
  vertexParticleGeo: null,
  vertexParticleStreams: [],
  particleCloudGeo: null,
  particleFlowElapsed: null,
  particleFlowLastUpdate: null,
  scene: null,
  camera: null,
  renderer: null,
  labelRenderer: null,
  controls: null,
  composer: null,
  effectTransition: null
};
