import {
  DEFAULT_PYRAMID_COLOR,
  DEFAULT_BRIGHTNESS,
  DEFAULT_SLICE_GRADIENTS,
  DEFAULT_SLICE_OPACITY,
  DEFAULT_AXIS_SETTINGS,
  DEFAULT_FOOT_SETTINGS,
  DEFAULT_SHELL_SETTINGS,
  DEFAULT_EDGE_FLOW_SETTINGS,
  DEFAULT_GRID_SETTINGS,
  DEFAULT_MOTION_PARTICLE_SETTINGS,
  DEFAULT_STRATEGIC_LABEL_POSITIONS,
  DEFAULT_STRATEGIC_LABEL_FONT_SIZE,
  DEFAULT_STRATEGIC_APEX_BG,
  PYRAMID_EFFECT_MODES
} from '../config/constants.js';

export const state = {
  pyramidColorHex: DEFAULT_PYRAMID_COLOR,
  pyramidBrightness: DEFAULT_BRIGHTNESS,
  sliceGradients: DEFAULT_SLICE_GRADIENTS.map((g) => ({ ...g })),
  sliceOpacity: { ...DEFAULT_SLICE_OPACITY },
  axisSettings: { ...DEFAULT_AXIS_SETTINGS },
  footSettings: { ...DEFAULT_FOOT_SETTINGS },
  shellSettings: { ...DEFAULT_SHELL_SETTINGS },
  edgeFlowSettings: { ...DEFAULT_EDGE_FLOW_SETTINGS },
  motionParticleSettings: { ...DEFAULT_MOTION_PARTICLE_SETTINGS },
  gridSettings: { ...DEFAULT_GRID_SETTINGS },
  strategicLabelPositions: Object.fromEntries(
    Object.entries(DEFAULT_STRATEGIC_LABEL_POSITIONS).map(([key, position]) => [key, { ...position }])
  ),
  strategicLabelFontSize: DEFAULT_STRATEGIC_LABEL_FONT_SIZE,
  strategicApexBg: {
    width: DEFAULT_STRATEGIC_APEX_BG.width,
    position: { ...DEFAULT_STRATEGIC_APEX_BG.position }
  },
  gridGroup: null,
  gridMaterial: null,
  gridRevealGroup: null,
  gridRevealMaterial: null,
  pyramidEffectMode: PYRAMID_EFFECT_MODES.GLOW,
  motionParticleGoldWeight: 1,
  pyramidGroups: { glow: null, wireframe: null, particles: null, flow: null },
  pyramidRootGroup: null,
  pyramidAutoRotate: false,
  glowObjects: null,
  pyramidMats: {},
  pyramidLights: {},
  bloomPass: null,
  fxaaPass: null,
  labelElements: [],
  strategicLabels: [],
  baseCornerMarkers: [],
  showCornerMarkers: false,
  clock: null,
  pyramidApex: null,
  pyramidBaseVerts: null,
  pyramidSliceHeights: null,
  internalParticleGeo: null,
  internalParticleStreams: [],
  particleCloudGeo: null,
  particleFlowElapsed: null,
  particleFlowLastUpdate: null,
  scene: null,
  camera: null,
  renderer: null,
  labelRenderer: null,
  controls: null,
  composer: null,
  effectTransition: null,
  cameraViewTransition: null,
  initialReveal: null
};
